# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: sieburger.com
title: Sieburger.com
email: sieb@gmx.us
author: M. Sieburger
description: sieburger P2P Bitcoin Exchange OTT
copyright: 'Copyright &copy; 2021 sieburger.com. All Rights Reserved.'
credits: 'Credits: <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/sabugosa4
#  - title: github
#   url: https://www.github.com/sieburger
#  - title: linkedin
#    url: 
  - title: facebook
    url: https://facebook.com/marcio.sieburger
